language: go

# fuse on travis
sudo: required
dist: xenial

git:
  depth: 300

# Build with the lastest versions of Go 1.7 and later
# See https://golang.org/dl/
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - stable

before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

install:
  - go get -d -t -v ./...
  - wget https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -O dep
  - chmod +x dep

script:
  - openssl version
  - df -Th / /tmp
  - go build
  - ./build-without-openssl.bash
  - ./build.bash
  - ./gocryptfs -speed
  - ./test.bash -v
  - ./crossbuild.bash
  - echo "rebuild with locked dependencies"
  - echo travis_fold:start:dep
  - ./dep ensure -v
  - echo travis_fold:end:dep
  - ./build.bash
